### ISSUE TITLE
Could not find analysis server snapshot

### ISSUE THREAD

**Issue by jnnks** [natebosch/vim-lsc-dart#11]
Opening a dart file throws following error:
```
Error detected while processing function lsc#dart#register[1]..<SNR>35_FindCommand:
line    6:
Could not find analysis server snapshot at /home/jannik/devenv/flutter/bin/snapshots/analysis_server.dart.snapshot
Error detected while processing function <SNR>14_OnOpen[4]..lsc#file#onOpen[3]..lsc#server#start[3]..<SNR>29_Start[41]..4[2]..7[4]..10[2]..12[2]..13[2]..14:
line    1:
E631: ch_sendraw(): write failed
Press ENTER or type command to continue
[lsc:Error] StdErr from dart_language_server: executing job failed: No such file or directory
[lsc:Error] Failed to initialize server: dart_language_server
```

How can i generate a snapshot?

**Comment by natebosch** [comment]
There are 2 issues here

The first is that when flutter added a `dart` command to their `bin/` directory it broke the logic here to find the right path for the SDK. I will take a look at fixing that.

The second is that it looks like you still have old config referencing `dart_language_server`. You should drop that.

**Comment by natebosch** [comment]
This should be fixed on the latest. I'd recommend also removing `'dart'` from your `g:lsc_server_commands` dict - or if it is currently the only entry you can remove it entirely.

**Comment by bitmage** [comment]
I'm using `snap` on Manjaro.  I found the correct directory for the SDK by running `snap run --shell flutter` and `echo $SNAP_USER_COMMON`.  Based on [these instructions](https://askubuntu.com/questions/762354/where-can-ubuntu-snaps-write-data).

Snap puts the flutter SDK at: `~/snap/flutter/common/flutter/bin/cache/dart-sdk/`.  Meanwhile `which flutter` returns `/var/lib/snapd/snap/bin/flutter`.  Snap's structure is pretty convoluted for our purposes.

What worked for me was to set `let g:lsc_dart_sdk_path = '~/snap/flutter/common/flutter/bin/cache/dart-sdk/'`.  This gets picked up by your `FindCommand` code [here](https://github.com/natebosch/vim-lsc-dart/blob/master/autoload/lsc/dart.vim#L25).  This feels simple and satisfactory.

You might consider documenting the `lsc_dart_sdk_path` variable, as it may solve problems for other folks as well.
