### ISSUE TITLE
Error: Could not find analysis server snapshot

### ISSUE THREAD

**Issue by ItsaMeTuni** [natebosch/vim-lsc-dart#20]
When I try opening a .dart file I immediately get a `Could not find analysis server snapshot` error. I have checked my `$PATH` and it has the flutter folder. Also, there is no `<flutter-folder>/bin/snapshots` folder, but there is a `<flutter-folder>/bin/cache/dart-sdk/bin/snapshots` folder with a `analysis_server.dart.snapshot` file in it.

Creating a `<flutter-folder>/bin/snapshots` symlink that points to `<flutter-folder>/bin/cache/dart-sdk/bin/snapshots` fixes the problem. However, I'm not sure if this is how it's supposed to be.

Here's the error:
```
Error detected while processing function lsc#dart#register[1]..<SNR>38_FindCommand:
line   14:
Could not find analysis server snapshot at /home/lucas/.local/lib/flutter/bin/snapshots/analysis_server.dart.snapsh
ot
```

Here's my `init.vim`:
```

call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dart-lang/dart-vim-plugin'
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf', {'do': { -> fzf#install() }}
Plug 'junegunn/fzf.vim'
Plug 'AndrewRadev/sideways.vim'
Plug 'natebosch/vim-lsc'
Plug 'natebosch/vim-lsc-dart'

call plug#end()

source $HOME/.config/nvim/plug-config/coc.vim 

" disable line wrapping
set nowrap

" show hybrid line numbers
set number relativenumber

set termguicolors

colorscheme gruvbox

let mapleader = ' '

nmap <leader>a <Plug>(coc-codeaction-selected)
map <leader>f :Files<CR>
nnoremap <leader>k gt
nnoremap <leader>j gT
nnoremap <leader>x :tabclose<CR>
nnoremap <c-h> :SidewaysLeft<CR>
nnoremap <c-l> :SidewaysRight<CR>

set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

let g:lsc_dart_sdk_path = "$HOME/.local/lib/flutter"
let g:dart_format_on_save = 1
let g:lsc_auto_map = v:true
```

Is this a problem with my flutter installation or could it be a bug in vim-lsc-dart?
I'm a newbie in vim and flutter, so this might my own fault...

Thanks for your help and for this plugin!

**Comment by natebosch** [comment]
Hmm, I think this is the same error behavior as the bug that should have been fixed with https://github.com/natebosch/vim-lsc-dart/commit/6fb2e7f997072c73c01acc9a19040afe5b126acf

Are you using a version which includes that commit?

If you are on the latest  version of `vim-lsc-dart` there is a workaround that _should_ always work, which is to add a `g:lsc_dart_sdk_path` variable to your vimrc with a hardcoded path the the Dart SDK that gets downloaded by flutter. See `:help g:lsc_dart_sdk_path`.

I think in your case it would be

```viml
let g:lsc_dart_sdk_path = '~/.local/lib/flutter/bin/cache/dart-sdk'
```

**Comment by ItsaMeTuni** [comment]
Sorry for taking this long to reply. Setting `lsc_dart_sdk_path` to a hardcoded path to the dart sdk solved the problem. Thank you very much!
