### ISSUE TITLE
How can I configure Dart analysis to run on HTML files?

### ISSUE THREAD

**Issue by leonsenft** [natebosch/vim-lsc-dart#4]
AngularDart has an analyzer plugin that analyzes component templates (which are typically in HTML files).

Previously with `dart_language_server` I configured it to run like this:

```vim
let g:lsc_server_commands = {
  \ 'dart': 'dart_language_server',
  \ 'html': 'dart_language_server' }
```

What is the equivalent configuration with this plugin now?

**Comment by natebosch** [comment]
I can either set this up unconditionally, or I could try to check the environment somehow to see if it should be enabled... Do you have any thoughts on whether it's worth adding a condition?

**Comment by leonsenft** [comment]
I think enabling conditionally is ideal, but that depends on how that can be achieved. For example, is it possible to ask the Dart analysis server whether it has the Angular plugin enabled, and if so, then turn on analysis for HTML files? @MichaelRFairhurst might have ideas.
